# Generated by Django 5.1.2 on 2024-11-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=2)),
                ('factor_rh', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('registro_medico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoTratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('registro_medico', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHemocomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('seguro', models.CharField(max_length=50)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.genero')),
                ('grupo_sanguineo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.gruposanguineo')),
            ],
        ),
        migrations.CreateModel(
            name='ReaccionTransfusional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_reaccion', models.DateField()),
                ('tipo_reaccion', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='transfusion_app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('urgencia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')])),
                ('diagnostico', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_autoriza', to='transfusion_app.medico')),
                ('medico_tratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.medicotratante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.paciente')),
                ('unidad_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.unidadtratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Hemocomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unidades_solicitadas', models.IntegerField()),
                ('solicitud_transfusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hemocomponentes', to='transfusion_app.solicitudtransfusion')),
                ('tipo_hemocomponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfusion_app.tipohemocomponente')),
            ],
        ),
    ]
